version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_crud_users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_users
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgnetwork

volumes:
  pgdata:

networks:
  pgnetwork: